# Generated by Django 4.2.9 on 2024-02-15 07:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


def add_default_plans(apps, schema_editor):
    plan = apps.get_model('userauth', 'Plan')
    plan.objects.create(id='d9c2f6d8-0a7a-4b0d-8e8c-3a2d5a5a5a5a', name='Platinum365', price=499, validity=365, status='active')
    plan.objects.create(id='02317da1-7859-4ae0-ab6a-bc39eda90124', name='Gold180', price=299, validity=180, status='active')
    plan.objects.create(id='1a4a52e8-8689-4582-9ad6-3a7ac71bd4be', name='Silver90', price=199, validity=90, status='active')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('validity', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')])),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField(null=True)),
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('phone_number', models.CharField(max_length=32)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('plan_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauth.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlackListedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_user', to='userauth.usermodel')),
            ],
            options={
                'unique_together': {('token', 'user')},
            },
        ),
        migrations.RunPython(add_default_plans)
    ]
