# Generated by Django 4.2.9 on 2024-02-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='adhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
